### PR TITLE
upgrade to latest wasmd and sdk

### PR DESCRIPTION
**Pull request by faddat**
This PR upgrades chihuhahua to the latest cosmos-sdk v0.45.x release.  It can be considered incremental.

### CODE REVIEW

**Review by lydia-pierce — APPROVED** [review]
LGTM except we'll use the chihuahua version of the sdk that I'll make real quick and add to this PR.

**Comment by lydia-pierce** [comment]
Still need to fix an error in the genwasm.go file and test on the testnet, then we can upgrade

**Comment by faddat** [comment]
cool, I'll take care of it

**Comment by faddat** [comment]
ohhhh
genwasm we just kill :)

**Comment by faddat** [comment]
confio moved this bit one layer up the stack is all.

**Comment by faddat** [comment]
thanks for catching the no-chihuahua-sdk bug that would have been sad face

**Pull request merged**
