### PR TITLE
sdk bump and go upgrade

### PR DESCRIPTION
**Pull request by faddat**
You might want to upgrade your upstream fork to 45.6. If you could let me know what changes in your SDK fork, that would be cool. Thank you

### CODE REVIEW

**Comment by lydia-pierce** [comment]
Thanks for these updates! There should just be two commits to ensure the we can set the minimum commission rate for the validators (the SDK includes this feature in v0.46.0 and beyond, but not in v0.45.x). Here are the two commits: [99ebd92](https://github.com/pomifer/cosmos-sdk/pull/4/commits/99ebd9271a5ea832454d737338d30082d7848b2e) and [37aa7a0](https://github.com/pomifer/cosmos-sdk/pull/4/commits/37aa7a0d34a57ad0c001c1031ae96c3fbf7237f1) which can be seen in both of these PRs: [#4](https://github.com/pomifer/cosmos-sdk/pull/4) and [#2](https://github.com/pomifer/cosmos-sdk/pull/2)

**Comment by lydia-pierce** [comment]
Thanks for making this PR @faddat ! We have decided we are just going to wait until the v0.46 release of the sdk, since it already includes minimum commission and other great features. Closing in favor of #31

**Comment by alanwilhelm** [comment]
It has been a while but I assume since cosmwasm is going to skip 46 you are as well?

**Comment by lydia-pierce** [comment]
@alanwilhelm We have and will use the most up-to-date version of the sdk that cosmwasm uses, so once they release a version with 47, we will use that

**Pull request closed without merging**
